# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RE-FUSE | music-theater platform
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  REFUSE | music-theater platform. An annual platform hosted in
  2016/17 by the Alternative Stage of the Greek National Opera
  in Athens (GR) and Gaudeamus in Utrecht (NL).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://re-fuse.github.io/" # the base hostname & protocol for your site
youtube_username: UC2wo8f6V1jrWrqPUbg98c1w
github_username:  Re-Fuse

# Build settings
markdown: kramdown
